languages:
  - en
  - pt
title:
  en: Samba's Lexicon
  pt: Léxico do Samba
description:
  en: Quais as palavras mais comuns em sambas? Que palavra é mais usada por cada sambista? Para responder essas e outras perguntas, o Léxico do Samba analisou 14,7 mil músicas, o que levou a 1,8 milhão de palavras.
  pt: Quais as palavras mais comuns em sambas? Que palavra é mais usada por cada sambista? Para responder essas e outras perguntas, o Léxico do Samba analisou 14,7 mil músicas, o que levou a 1,8 milhão de palavras.
thumbnail:
  en: "https://www.lexicodosamba.com.br/assets/img/social-thumb.png"
  pt: "https://www.lexicodosamba.com.br/assets/img/social-thumb.png"
baseurl: ""
url: ""
